### ISSUE TITLE
3.1.0 version doesn't work well with PHP 7

### ISSUE THREAD

**Issue by wanglingsong** [phpredis/phpredis#1096]
I'm running an application with phpredis extention 3.1.0 and php 7 in docker.
The php-fpm process keep throwing following error message:
php-fpm child process exited on signal 11
When I downgrade the phpredis to 3.0.0 or downgrade php to 5.6, the error gone.

**Comment by yatsukhnenko** [comment]
@wanglingsong, many errors were fixed in 3.1.1RC. Could you test it?

**Comment by wanglingsong** [comment]
Sure. Will do later

**Comment by dzuelke** [comment]
@wanglingsong any update?

**Comment by wanglingsong** [comment]
Sorry. I'm on vacation now. I will test it next week.

**Comment by wanglingsong** [comment]
@dzuelke I tested it on 3.1.1 and 3.1.1RC2. Both failed and still throw the error which make some of http requests become 501 bad gateway

**Comment by dzuelke** [comment]
So do you have a reproduce case?

**Comment by wanglingsong** [comment]
Please clone "phpredis(#1096)" of this project:
```git clone https://github.com/wanglingsong/laradock.git --branch "phpredis(#1096)"```
My project is running inside Docker so you have to start it by ```docker-compose up nginx``` under the project root.
Once started, you just need to refresh the homepage "localhost:80" several times then you might see some error in the logs of php-fpm as below
```
[06-Feb-2017 10:36:11] NOTICE: fpm is running, pid 1
[06-Feb-2017 10:36:11] NOTICE: ready to handle connections
[06-Feb-2017 10:36:16] WARNING: [pool www] child 7 exited on signal 11 (SIGSEGV) after 4.674266 seconds from start
[06-Feb-2017 10:36:16] NOTICE: [pool www] child 9 started
172.18.0.5 -  06/Feb/2017:10:36:41 +0000 "GET /index.php" 200
172.18.0.5 -  06/Feb/2017:10:36:48 +0000 "GET /index.php" 200
172.18.0.5 -  06/Feb/2017:10:36:49 +0000 "GET /index.php" 200
172.18.0.5 -  06/Feb/2017:10:36:51 +0000 "GET /index.php" 200
[06-Feb-2017 10:37:13] WARNING: [pool www] child 8 said into stderr: "zend_mm_heap corrupted"
[06-Feb-2017 10:37:13] WARNING: [pool www] child 8 exited with code 1 after 61.475305 seconds from start
[06-Feb-2017 10:37:13] NOTICE: [pool www] child 10 started
[06-Feb-2017 10:38:33] WARNING: [pool www] child 9 said into stderr: "zend_mm_heap corrupted"
[06-Feb-2017 10:38:33] WARNING: [pool www] child 9 exited with code 1 after 137.011551 seconds from start
[06-Feb-2017 10:38:33] NOTICE: [pool www] child 11 started
```

**Comment by dzuelke** [comment]
Well, by "reproduce" case I meant a single script or something that exhibits the behavior :) If you can rebuild your setup with a debug build of php-fpm, that'd at least make it easier. Then you or someone else can dig deeper with Valgrind et al.

**Comment by michael-grunder** [comment]
I'm pretty sure this has been fixed in 3.1.2

**Comment by wanglingsong** [comment]
Tested in 3.1.2. It works without error. Thanks!

**Comment by apurvanagarkoti-powerschool** [comment]
how to downgrade php redis version
