### ISSUE TITLE
session locking requires redis 2.6.12 but docs say 2.0

### ISSUE THREAD

**Issue by amfleurke** [phpredis/phpredis#1482]
### Expected behaviour
Redis 2.4 supported, or documentation saying redis 2.6.12 required (SET + EX / NX options)
### Actual behaviour
php hangs on connecting to redis 2.4, because the set command has wrong number of arguments, in combination with https://github.com/phpredis/phpredis/issues/1412 and doesn't report any error whatsoever
documentation says "The session handler requires a version of Redis with the SETEX command (at least 2.0)."

### I'm seeing this behaviour on
- OS: CentOS
- Redis: 2.4
- PHP: 5.6.30
- phpredis: 4.2.0

### Steps to reproduce, backtrace or example script
enable session locking, request a webpage.

strace shows
nanosleep({0, 50000000}, NULL)          = 0
poll([{fd=18, events=POLLIN|POLLPRI|POLLERR|POLLHUP}], 1, 0) = 0 (Timeout)
sendto(18, "*6\r\n$3\r\nSET\r\n$62\r\nPHPREDIS_SESSI"..., 134, MSG_DONTWAIT, NULL, 0) = 134
poll([{fd=18, events=POLLIN|POLLPRI|POLLERR|POLLHUP}], 1, 0) = 0 (Timeout)
poll([{fd=18, events=POLLIN|POLLERR|POLLHUP}], 1, 60000) = 1 ([{fd=18, revents=POLLIN}])
recvfrom(18, "-ERR wrong number of arguments f"..., 8192, MSG_DONTWAIT, NULL, NULL) = 50
nanosleep({0, 50000000}, NULL)          = 0
etc. etc.

### I've checked
- [X] There is no similar issue from other users
- [X] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
@amfleurke this should be fixed in `issue-1412` branch. Could you test it?

**Comment by amfleurke** [comment]
Hi Pavlo, thanks for trying to fix this.

I checked out your branch, ran mkdev.sh to get the .so file, and put it in the modules dir, and restarted apache. phpinfo shows a 4.2.0 ce063cfa00628fd544909da854fe87d9145dc0dd phpredis is installed now. But I still get


sendto(18, "*6\r\n$3\r\nSET\r\n$62\r\nPHPREDIS_SESSI"..., 134, MSG_DONTWAIT, NULL, 0) = 134
poll([{fd=18, events=POLLIN|POLLPRI|POLLERR|POLLHUP}], 1, 0) = 0 (Timeout)
poll([{fd=18, events=POLLIN|POLLERR|POLLHUP}], 1, 60000) = 1 ([{fd=18, revents=POLLIN}])
recvfrom(18, "-ERR wrong number of arguments f"..., 8192, MSG_DONTWAIT, NULL, NULL) = 50
nanosleep({0, 50000000},

in strace, and not responding website.

**Comment by yatsukhnenko** [comment]
Could you show INI settings for `redis.session`?

**Comment by amfleurke** [comment]
session.save_path = "tcp://myredishost:6379?database=3"
redis.session.locking_enabled = 1
redis.session.lock_wait_time = 50000
redis.session.lock_retries = -1

**Comment by yatsukhnenko** [comment]
> lock_retries = -1

You infinitely try to lock and since your redis server is very old and not support extra set arguements all tries fail

**Comment by amfleurke** [comment]
correct. So it would be good to add to the documentation that redis 2.4 is not supported.
changing lock_retries to something else will make the session locking not working any more. 
( I can't really think of an use case for a different value than -1: you want to get a lock only when other threads have ended their lock, not after x retries)

**Comment by yatsukhnenko** [comment]
I'll add a notice in documentation

**Comment by yatsukhnenko** [comment]
I updated minimum server version in documentation
