### ISSUE TITLE
strncmp fatal error, missing 3rd argument with php8.2

### ISSUE THREAD

**Issue by torbentomtrust** [phpredis/phpredis#2565]
### Actual behaviour

Compilation says that strncmp needs 3 arguments instead of 2.
In redis.c there are lines that include this  :   strncmp(resp, ZEND_STRL("+OK"))
It should be replaced by strncmp(resp, "+OK", 3)

As far as I noticed there are 3 occurences in redis.c

### I'm seeing this behaviour on
- OS: CentOs
- Redis: 6.1.0
- PHP: 8.2
- phpredis:

### Steps to reproduce, backtrace or example script
Compiling on Centos with CPanel

### I've checked
- [ ] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
@torbentomtrust please add more details

**Comment by torbentomtrust** [comment]
@yatsukhnenko I added more details in the description. Thank you !!

**Comment by michael-grunder** [comment]
> Compilation says that strncmp needs 3 arguments instead of 2.

Are you actually seeing a compiler error? If so can you paste the actual message along with what compiler and version you're trying to build with?

`ZEND_STRL` is a macro:

```c
#define ZEND_STRL(str)		(str), (sizeof(str)-1)
```

So `strncmp(var, ZEND_STRL("+OK"));` will expand to:

```c
strncmp(var, "+OK", 3);
```

We do have to avoid this idiom for some comparisons because Windows defines a few standard C library functions as macros, but we have never seen this issue on any Linux or Linux-like system.

**Comment by torbentomtrust** [comment]
@michael-grunder  thank you for your answer!

I'm actually using CPanel and there is a PECL module installer in WHM. When I use this module and try to install redis for php 8.2 I get this error.
Unfortunately we installed an older version now and I can't run this again on this server, but I can setup another server with the same settings and try.

**Comment by torbentomtrust** [comment]
I tried on another server and get the error, here is the output :

WARNING: channel "pecl.php.net" has updated its protocols, use "pecl channel-update pecl.php.net" to
 update
downloading redis-6.1.0.tgz ...
Starting to download redis-6.1.0.tgz (373,740 bytes)
.............................................................................done: 373,740 bytes
43 source files, building
running: phpize
Configuring for:
PHP Api Version:         20220829
Zend Module Api No:      20220829
Zend Extension Api No:   420220829
enable igbinary serializer support? [no] : enable lzf compression support? [no] : enable zstd compre
ssion support? [no] : enable msgpack serializer support? [no] : enable lz4 compression? [no] : use s
ystem liblz4? [yes] : building in /root/tmp/pear/pear-build-rootaQcBse/redis-6.1.0
running: /root/tmp/pear/redis/configure --with-php-config=/opt/cpanel/ea-php82/root/usr/bin/php-conf
ig --enable-redis-igbinary=no --enable-redis-lzf=no --enable-redis-zstd=no --enable-redis-msgpack=no
 --enable-redis-lz4=no --with-liblz4
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for pkg-config... /bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking for system library directory... lib
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for PHP prefix... /opt/cpanel/ea-php82/root/usr
checking for PHP includes... -I/opt/cpanel/ea-php82/root/usr/include/php -I/opt/cpanel/ea-php82/root
/usr/include/php/main -I/opt/cpanel/ea-php82/root/usr/include/php/TSRM -I/opt/cpanel/ea-php82/root/u
sr/include/php/Zend -I/opt/cpanel/ea-php82/root/usr/include/php/ext -I/opt/cpanel/ea-php82/root/usr/
include/php/ext/date/lib
checking for PHP extension directory... /opt/cpanel/ea-php82/root/usr/lib64/php/modules
checking for PHP installed headers prefix... /opt/cpanel/ea-php82/root/usr/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for gawk... gawk
checking whether to enable redis support... yes, shared
checking whether to enable sessions... yes
checking whether to enable json serializer support... yes
checking whether to enable igbinary serializer support... no
checking whether to enable msgpack serializer support... no
checking whether to enable lzf compression... no
checking use system liblzf... no
checking whether to enable Zstd compression... no
checking use system libzstd... yes
checking whether to enable lz4 compression... no
checking use system liblz4... yes
checking for hash includes... /opt/cpanel/ea-php82/root/usr/include/php
checking for json includes... /opt/cpanel/ea-php82/root/usr/include/php
checking for redis json support... enabled
checking for redis igbinary support... disabled
checking for pkg-config... /bin/pkg-config
checking for git... yes
checking how to print strings... printf
checking for a sed that does not truncate output... (cached) /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by cc... /bin/ld
checking if the linker (/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /bin/nm -B
checking the name lister (/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 3458764513820540925
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert
_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop

checking for /bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking for gawk... (cached) gawk
checking command to parse /bin/nm -B output from cc object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC -DPIC
checking if cc PIC flag -fPIC -DPIC works... yes
checking if cc static flag -static works... yes
checking if cc supports -c -o file.o... yes
checking if cc supports -c -o file.o... (cached) yes
checking whether the cc linker (/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
configure: patching config.h.in
configure: creating ./config.status
config.status: creating config.h
config.status: executing libtool commands
running: make
/bin/sh /root/tmp/pear/pear-build-rootaQcBse/redis-6.1.0/libtool --tag=CC --mode=compile cc -I. -I/r
oot/tmp/pear/redis -I/root/tmp/pear/pear-build-rootaQcBse/redis-6.1.0/include -I/root/tmp/pear/pear-
build-rootaQcBse/redis-6.1.0/main -I/root/tmp/pear/redis -I/opt/cpanel/ea-php82/root/usr/include/php
 -I/opt/cpanel/ea-php82/root/usr/include/php/main -I/opt/cpanel/ea-php82/root/usr/include/php/TSRM -
I/opt/cpanel/ea-php82/root/usr/include/php/Zend -I/opt/cpanel/ea-php82/root/usr/include/php/ext -I/o
pt/cpanel/ea-php82/root/usr/include/php/ext/date/lib -I/opt/cpanel/ea-php82/root/usr/include/php/ext
  -DHAVE_CONFIG_H  -g -O2 -D_GNU_SOURCE    -DZEND_COMPILE_DL_EXT=1 -c /root/tmp/pear/redis/redis.c -
o redis.lo  -MMD -MF redis.dep -MT redis.lo
libtool: compile:  cc -I. -I/root/tmp/pear/redis -I/root/tmp/pear/pear-build-rootaQcBse/redis-6.1.0/
include -I/root/tmp/pear/pear-build-rootaQcBse/redis-6.1.0/main -I/root/tmp/pear/redis -I/opt/cpanel
/ea-php82/root/usr/include/php -I/opt/cpanel/ea-php82/root/usr/include/php/main -I/opt/cpanel/ea-php
82/root/usr/include/php/TSRM -I/opt/cpanel/ea-php82/root/usr/include/php/Zend -I/opt/cpanel/ea-php82
/root/usr/include/php/ext -I/opt/cpanel/ea-php82/root/usr/include/php/ext/date/lib -I/opt/cpanel/ea-
php82/root/usr/include/php/ext -DHAVE_CONFIG_H -g -O2 -D_GNU_SOURCE -DZEND_COMPILE_DL_EXT=1 -c /root
/tmp/pear/redis/redis.c -MMD -MF redis.dep -MT redis.lo  -fPIC -DPIC -o .libs/redis.o
/root/tmp/pear/redis/redis.c: In function 'zim_Redis_multi':
/root/tmp/pear/redis/redis.c:1909:58: error: macro "strncmp" requires 3 arguments, but only 2 given
                 } else if (strncmp(resp, ZEND_STRL("+OK")) != 0) {
                                                          ^
/root/tmp/pear/redis/redis.c: In function 'redis_response_enqueued':
/root/tmp/pear/redis/redis.c:2048:47: error: macro "strncmp" requires 3 arguments, but only 2 given
         if (strncmp(resp, ZEND_STRL("+QUEUED")) == 0) {
                                               ^
/root/tmp/pear/redis/redis.c: In function 'redis_sock_read_multibulk_multi_reply_loop':
/root/tmp/pear/redis/redis.c:2072:44: error: macro "strncmp" requires 3 arguments, but only 2 given
             strncmp(inbuf, ZEND_STRL("+OK")) != 0)
                                            ^
make: *** [redis.lo] Error 1
ERROR: `make' failed

**Comment by michael-grunder** [comment]
It's because `strncmp` on this system is a macro.

```
/root/tmp/pear/redis/redis.c: In function 'redis_response_enqueued':
/root/tmp/pear/redis/redis.c:2048:47: error: macro "strncmp" requires 3 arguments, but only 2 given
if (strncmp(resp, ZEND_STRL("+QUEUED")) == 0) {
```

I've never seen this on a Linux system before. It's simple enough to fix although i think there are a few more `strncmp` invocations in files other than redis.c

**Comment by yatsukhnenko** [comment]
> I've never seen this on a Linux system before

It is actually a rhel based distro with commercial support and own packages repository

I've set up VM with CloudLinux 8 and verifyed that build with PHP from Remi's repo works fine
```
Build process completed successfully
Installing '/usr/lib64/php/modules/redis.so'
install ok: channel://pecl.php.net/redis-6.1.0
configuration option "php_ini" is not set to php.ini location
You should add "extension=redis.so" to php.ini
```

So issue is probably with PHP from CloudLinux's repo but I didn;t check because it requires license to install those packages

**Comment by jaapl** [comment]
Hello, FWIW: we're seeing these errors on RHEL7 and on RHEL8 as well.
No errors on RHEL9.

```
/tmp/pear/temp/redis/redis.c: In function 'zim_Redis_multi':
/tmp/pear/temp/redis/redis.c:1909:58: error: macro "strncmp" requires 3 arguments, but only 2 given
                 } else if (strncmp(resp, ZEND_STRL("+OK")) != 0) {
                                                          ^
/tmp/pear/temp/redis/redis.c: In function 'redis_response_enqueued':
/tmp/pear/temp/redis/redis.c:2048:47: error: macro "strncmp" requires 3 arguments, but only 2 given
         if (strncmp(resp, ZEND_STRL("+QUEUED")) == 0) {
                                               ^
/tmp/pear/temp/redis/redis.c: In function 'redis_sock_read_multibulk_multi_reply_loop':
/tmp/pear/temp/redis/redis.c:2072:44: error: macro "strncmp" requires 3 arguments, but only 2 given
             strncmp(inbuf, ZEND_STRL("+OK")) != 0)
                                            ^
make: *** [Makefile:210: redis.lo] Error 1
```

**Comment by michael-grunder** [comment]
Let me know if the #2567 branch compiles for everyone.

I don't know what's going on with GitHub CI but the jobs are getting stuck. It shouldn't be related to this change so hopefully they'll get unstuck on their own.

Edit: What was going on with CI is I did `ubuntu:22.04` instead of `ubuntu-22.04` 🥴

**Comment by jaapl** [comment]
Thanks for the quick response! Almost there it seems:
```
phpredis/cluster_library.c: In function 'cluster_type_resp':
phpredis/cluster_library.c:1913:55: error: macro "strncmp" requires 3 arguments, but only 2 given
     } else if (strncmp(c->line_reply, ZEND_STRL("set")) == 0) {
                                                       ^
make: *** [Makefile:231: cluster_library.lo] Error 1
```
Just one more occurrence - after changing the following the build is working:
```
--- a/cluster_library.c
+++ b/cluster_library.c
@@ -1910,7 +1910,7 @@ PHP_REDIS_API void cluster_type_resp(INTERNAL_FUNCTION_PARAMETERS, redisCluster
     // Switch on the type
     if (redis_strncmp(c->line_reply, ZEND_STRL("string")) == 0) {
         CLUSTER_RETURN_LONG(c, REDIS_STRING);
-    } else if (strncmp(c->line_reply, ZEND_STRL("set")) == 0) {
+    } else if (redis_strncmp(c->line_reply, ZEND_STRL("set")) == 0) {
         CLUSTER_RETURN_LONG(c, REDIS_SET);
     } else if (redis_strncmp(c->line_reply, ZEND_STRL("list")) == 0) {
         CLUSTER_RETURN_LONG(c, REDIS_LIST);
```

**Comment by michael-grunder** [comment]
Thanks, should be fixed now.

**Comment by jaapl** [comment]
Confirmed: build is working without issue now. Thanks for the quick resolution!

**Comment by torbentomtrust** [comment]
I'm sorry I have been busy and didn't have a clue how I could test the version on the CPanel server since the module installer there gets the packages from some preset url.
However thank you so much @michael-grunder and @jaapl for fixing and testing! :)

**Comment by odhiambo** [comment]
I am still seeing this error in CentOS:
```
root@tra.transworldafrica.com [~]# /opt/cpanel/ea-php83/root/usr/bin/pecl install igbinary igbinary-devel redis
Ignoring installed package pecl/igbinary
Ignoring installed package pecl/igbinary
downloading redis-6.1.0.tgz ...
Starting to download redis-6.1.0.tgz (373,740 bytes)
.............................................................................done: 373,740 bytes
43 source files, building
running: phpize
Configuring for:
PHP Api Version:         20230831
Zend Module Api No:      20230831
Zend Extension Api No:   420230831
enable igbinary serializer support? [no] :
enable lzf compression support? [no] :
enable zstd compression support? [no] :
enable msgpack serializer support? [no] :
enable lz4 compression? [no] :
use system liblz4? [yes] :
building in /root/tmp/pear/pear-build-rootpIzrSB/redis-6.1.0
running: /root/tmp/pear/redis/configure --with-php-config=/opt/cpanel/ea-php83/root/usr/bin/php-config --enable-redis-igbinary=no --enable-redis-lzf=no --enable-redis-zstd=no --enable-redis-msgpack=no --enable-redis-lz4=no --with-liblz4
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking for system library directory... lib
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for PHP prefix... /opt/cpanel/ea-php83/root/usr
checking for PHP includes... -I/opt/cpanel/ea-php83/root/usr/include/php -I/opt/cpanel/ea-php83/root/usr/include/php/main -I/opt/cpanel/ea-php83/root/usr/include/php/TSRM -I/opt/cpanel/ea-php83/root/usr/include/php/Zend -I/opt/cpanel/ea-php83/root/usr/include/php/ext -I/opt/cpanel/ea-php83/root/usr/include/php/ext/date/lib
checking for PHP extension directory... /opt/cpanel/ea-php83/root/usr/lib64/php/modules
checking for PHP installed headers prefix... /opt/cpanel/ea-php83/root/usr/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for gawk... gawk
checking whether to enable redis support... yes, shared
checking whether to enable sessions... yes
checking whether to enable json serializer support... yes
checking whether to enable igbinary serializer support... no
checking whether to enable msgpack serializer support... no
checking whether to enable lzf compression... no
checking use system liblzf... no
checking whether to enable Zstd compression... no
checking use system libzstd... yes
checking whether to enable lz4 compression... no
checking use system liblz4... yes
checking for hash includes... /opt/cpanel/ea-php83/root/usr/include/php
checking for json includes... /opt/cpanel/ea-php83/root/usr/include/php
checking for redis json support... enabled
checking for redis igbinary support... disabled
checking for pkg-config... /usr/bin/pkg-config
checking for git... yes
checking how to print strings... printf
checking for a sed that does not truncate output... (cached) /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking for gawk... (cached) gawk
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC -DPIC
checking if cc PIC flag -fPIC -DPIC works... yes
checking if cc static flag -static works... yes
checking if cc supports -c -o file.o... yes
checking if cc supports -c -o file.o... (cached) yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
configure: patching config.h.in
configure: creating ./config.status
config.status: creating config.h
config.status: executing libtool commands
running: make
/bin/sh /root/tmp/pear/pear-build-rootpIzrSB/redis-6.1.0/libtool --tag=CC --mode=compile cc -I. -I/root/tmp/pear/redis -I/root/tmp/pear/pear-build-rootpIzrSB/redis-6.1.0/include -I/root/tmp/pear/pear-build-rootpIzrSB/redis-6.1.0/main -I/root/tmp/pear/redis -I/opt/cpanel/ea-php83/root/usr/include/php -I/opt/cpanel/ea-php83/root/usr/include/php/main -I/opt/cpanel/ea-php83/root/usr/include/php/TSRM -I/opt/cpanel/ea-php83/root/usr/include/php/Zend -I/opt/cpanel/ea-php83/root/usr/include/php/ext -I/opt/cpanel/ea-php83/root/usr/include/php/ext/date/lib -I/opt/cpanel/ea-php83/root/usr/include/php/ext  -DHAVE_CONFIG_H  -g -O2 -D_GNU_SOURCE    -DZEND_COMPILE_DL_EXT=1 -c /root/tmp/pear/redis/redis.c -o redis.lo  -MMD -MF redis.dep -MT redis.lo
libtool: compile:  cc -I. -I/root/tmp/pear/redis -I/root/tmp/pear/pear-build-rootpIzrSB/redis-6.1.0/include -I/root/tmp/pear/pear-build-rootpIzrSB/redis-6.1.0/main -I/root/tmp/pear/redis -I/opt/cpanel/ea-php83/root/usr/include/php -I/opt/cpanel/ea-php83/root/usr/include/php/main -I/opt/cpanel/ea-php83/root/usr/include/php/TSRM -I/opt/cpanel/ea-php83/root/usr/include/php/Zend -I/opt/cpanel/ea-php83/root/usr/include/php/ext -I/opt/cpanel/ea-php83/root/usr/include/php/ext/date/lib -I/opt/cpanel/ea-php83/root/usr/include/php/ext -DHAVE_CONFIG_H -g -O2 -D_GNU_SOURCE -DZEND_COMPILE_DL_EXT=1 -c /root/tmp/pear/redis/redis.c -MMD -MF redis.dep -MT redis.lo  -fPIC -DPIC -o .libs/redis.o
/root/tmp/pear/redis/redis.c: In function 'zim_Redis_multi':
/root/tmp/pear/redis/redis.c:1909:58: error: macro "strncmp" requires 3 arguments, but only 2 given
                 } else if (strncmp(resp, ZEND_STRL("+OK")) != 0) {
                                                          ^
/root/tmp/pear/redis/redis.c: In function 'redis_response_enqueued':
/root/tmp/pear/redis/redis.c:2048:47: error: macro "strncmp" requires 3 arguments, but only 2 given
         if (strncmp(resp, ZEND_STRL("+QUEUED")) == 0) {
                                               ^
/root/tmp/pear/redis/redis.c: In function 'redis_sock_read_multibulk_multi_reply_loop':
/root/tmp/pear/redis/redis.c:2072:44: error: macro "strncmp" requires 3 arguments, but only 2 given
             strncmp(inbuf, ZEND_STRL("+OK")) != 0)
                                            ^
make: *** [redis.lo] Error 1
ERROR: `make' failed
root@tra.transworldafrica.com [~]#
```

It's happening for both PHP7.4 and PHP8.3
How can I fix this?

**Comment by michael-grunder** [comment]
Unfortunately, we fixed this after 6.1.0 GA, so you must pull the source from GitHub and build manually.

[Diff between develop and 6.1.0](https://github.com/phpredis/phpredis/compare/6.1.0...develop)

There are only a couple of changes from 6.1.0 (this strncmp fix, and an XCLAIM bug fix) so it should be stable.

We can make a point of releasing 6.1.1 soon.

**Comment by odhiambo** [comment]
@michael-grunder, thank you very much. I have finally managed to manually install and activate.

**Comment by torbentomtrust** [comment]
@odhiambo , do you happen to remember the procedure, since I'm using CentOS I'd be happy if you can share! :)

**Comment by odhiambo** [comment]
@torbentomtrust Yes, I do remember somehow. However, I was installing this for cPanel as you might have realized already.
I followed https://github.com/phpredis/phpredis/blob/develop/INSTALL.md, with adaptations.
Please ensure that you do the same.

Because lz4 PHP extension was necessary for me too, I installed it first:
```
# yum install liblz4-dev
# git clone --recursive --depth=1 https://github.com/kjdev/php-ext-lz4.git
# cd php-ext-lz4
# /opt/cpanel/ea-php83/root/usr/bin/phpize
# ./configure --with-php-config=/opt/cpanel/ea-php83/root/usr/bin/php-config
# make && make install
```

Next I installed phpredis extension
```
# git clone https://github.com/phpredis/phpredis.git
# cd phpredis
# /opt/cpanel/ea-php83/root/usr/bin/phpize
# /opt/cpanel/ea-php83/root/usr/bin/pecl install igbinary igbinary-devel (Here I'm not too sure if I installed igbinary-devel)
# ./configure --enable-redis-igbinary --enable-redis-lz4 --with-liblz4 --with-php-config=/opt/cpanel/ea-php83/root/usr/bin/php-config
# make && make install
```

Enable the extensions:
```
# echo "extension=redis.so" > /opt/cpanel/ea-php83/root/etc/php.d/20-redis.ini
# echo "extension=lz4.so" > /opt/cpanel/ea-php83/root/etc/php.d/20-lz4.ini
```

Restart httpd and php-fpm daemons
Ensure the extensions are truly enabled:
```
root@train [phpredis]# /opt/cpanel/ea-php83/root/usr/bin/php -m | grep 'lz4\|redis'
lz4
redis
```

NB: I got valuable help from https://talk.plesk.com/threads/install-lz4-for-phpredis.368568/

HTH

**Comment by torbentomtrust** [comment]
@odhiambo Thank you so much for the detailed explanation, I appreciate really!! 👍 
Yes we have CPanel too, we will try this.
Have a wonderful day :)
Cheers,
Torben
