### ISSUE TITLE
incr/incrby

### ISSUE THREAD

**Issue by tianpomin** [phpredis/phpredis#844]
# my phpredis version:
 php -i | grep Redis
Redis Support => enabled
Redis Version => 2.2.8-dev

# code:

`$redis = new Redis();
$result = $redis->connect($redis_conf['host'], $redis_conf['port'], $redis_conf['timeout']);
$redis->auth($redis_conf['password']);
$key = 'FL1337871791_PC:20160629_test_tian';
$key1 = 'FL1337871791_PC:20160629_test_tian1';
$v1 = 2147483647;

$redis->set($key, 0);
$redis->set($key1, 0);
echo("incr:\t".$redis->incr($key, $v1)."\n");
echo("incry:\t".$redis->incrby($key1, $v1)."\n");

echo "--------------v2------------\n";

$v2 = 2147483648;
$redis->set($key, 0);
$redis->set($key1, 0);
echo("incr:\t".$redis->incr($key, $v2)."\n");
echo("incry:\t".$redis->incrby($key1, $v2)."\n");`

# output:
incr:	2147483647
incry:	2147483647
--------------v2------------
incr:	-2147483648
incry:	2147483648

i incr a  positive number,  but the result is negative,  it seems like that the max positive number  incr can support is  2147483647.   is it by design?

**Comment by michael-grunder** [comment]
Thanks for the report, this is indeed a bug.

**Comment by michael-grunder** [comment]
Please try again.  This should be fixed in develop and php7 now

**Comment by Jerry-Shaw** [comment]
Hi, all. Just tested the latest one of php7 on windows 7 x64 with redis 3.0, but the "testIncrby" showed failed when I run the testRedis script. Is there anything matter with the issue here? Remember that the test of "testIncrby" should be passed before.

**Comment by michael-grunder** [comment]
Tests pass for me on `develop` branch and `php7` branch:

```bash
➜  phpredis git:(develop) ✗ php55 tests/TestRedis.php --test incr
Note: these tests might take up to a minute. Don't worry :-)
Testing class Redis
testIncr        [PASSED]
testIncrByFloat [PASSED]


All tests passed. \o/
➜  phpredis git:(develop) ✗ php7 tests/TestRedis.php --test incr
Note: these tests might take up to a minute. Don't worry :-)
Testing class Redis
testIncr        [PASSED]
testIncrByFloat [PASSED]
```

Are you running the code from the `php7` branch or from 3.0.0 (e.g. PECL)?  There won't be another PECL release until a few more items are fixed.

**Comment by Jerry-Shaw** [comment]
I'll compiled a new one and make another test, still failed as follows.
![image](https://cloud.githubusercontent.com/assets/13212198/16538083/a41f3f1c-404a-11e6-907b-abc93f241a1a.png)
 

Is there something matter about the system? Mine is under Win7 x64, PHP 7.0.8.

**Comment by michael-grunder** [comment]
I don't have any Windows computer to test this on, so all I can do is guess.  The fact that testExpireAtWithLong also fails leads me to believe there is a problem in `redis_long_response` (library.c) under Windows, or at least your version of windows.

There is this block there:
```c
#ifdef PHP_WIN32
        __int64 ret = _atoi64(response + 1);
#else
        long long ret = atoll(response + 1);
#endif
```

My guess is that this is broken somehow under Windows, but why it would be broken under 64 bit windows is beyond me.  I don't know how familiar you are with C, but you can always put a debug line inside of that function (right after the call to _atoi64) to see what it's being converted to:

```c
php_printf("%ul", ret);
```

You might have to just use printf, because I don't know how that's translated in windows:

Something like this:

```c
printf("%I64d\n", ret);
```

**Comment by michael-grunder** [comment]
This could also be a problem formatting the command.

If you run this script:

```php
➜  phpredis git:(develop) ✗ cat /tmp/sincr.php
<?php
$r = new Redis();
$r->connect('127.0.0.1', 6379);

$r->del('incr-key');
var_dump($r->incrby('incr-key', 2147483648));
?>
```

And monitor your redis-server, what does the INCRBY command show up as.  Mine looks like this:

```bash
1467433438.266570 [0 127.0.0.1:54414] "INCRBY" "incr-key" "2147483648"
```

**Comment by Jerry-Shaw** [comment]
OK, that seems to be the problem. 

I am not good at C, but could try to find the issue on Windows following your suggestion.

**Comment by Jerry-Shaw** [comment]
I'll try it on Win 10 x64 LTSB later.

**Comment by Jerry-Shaw** [comment]
But, how can I tell the printf("%I64d\n", ret) return values?
Under Win10 x64 LTSB.
![image](https://cloud.githubusercontent.com/assets/13212198/16539820/19cf5c34-4081-11e6-8029-898b64064370.png)

I cannot monitor the redis-server under windows, but when I run the script, it showed three values as below
![image](https://cloud.githubusercontent.com/assets/13212198/16539826/51b4fb40-4081-11e6-9189-9a146b5e6bf6.png)

I test the redis server by incrby 2147483648 from 2, result is OK, it gives 2147483650.

What you thought is right, atoi64 may be converted incorrectly under windows even under x64 platform using Visual Studio 2015 with Update 3 when compiling.

**Comment by michael-grunder** [comment]
Is there a reason you can't monitor a redis instance.  Can you just start one locally and test against that?  It's possible that the failure is occurring when converting the long to a string, and not the response from redis.

**Comment by Jerry-Shaw** [comment]
Emmm... I can only monitor this under Windows... Seems useless.
![image](https://cloud.githubusercontent.com/assets/13212198/16549019/a736d84e-41cc-11e6-91d8-b9c2c6a7e53f.png)

**Comment by michael-grunder** [comment]
Oh i mean go into redis-cli and type monitor

**Comment by Jerry-Shaw** [comment]
OK. I just know that cli could be a monitor. it shows 
![image](https://cloud.githubusercontent.com/assets/13212198/16549287/180b19e2-41d0-11e6-9a9a-2157f267bbee.png)

And, I noticed that VS2015 gives a lot of 'warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data', and other warnings. Could those be some reasons?
![image](https://cloud.githubusercontent.com/assets/13212198/16549306/50899992-41d0-11e6-95fa-205fdab92140.png)

**Comment by michael-grunder** [comment]
OK I believe I can get this solved for you.  It's happening when building the incrby command.

I think I know what's happening

**Comment by Jerry-Shaw** [comment]
I am tracking the data convertion, but without luck. Haha, may need to learn some C, which could help in the future.

**Comment by michael-grunder** [comment]
C is the best language :)

**Comment by Jerry-Shaw** [comment]
:<     Yep...
I'll try, but, maybe too complex for me?

**Comment by michael-grunder** [comment]
It's not too complex, just different.  Happy to explain the fix when I post it.  :)

**Comment by Jerry-Shaw** [comment]
:)   Haha, always happy to learn. It may be a new world for me.
